project:
  type: website

website:
  title: "ISSS622-GAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1.1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.1.html" 
          - text: "Hands-on Exercise 1.2"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.2.html"
            
      - text: "In-class Exercise"
        menu: 
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"

      - text: "Take-home Exercise"
        menu: 
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: Zephyr
      dark: darkly
    css: styles.css
    toc: true
    toc-location: left
    grid: 
      body-width: 1500px
      sidebar-width: 300px
      margin-width:	150px

